use crate::action::ActionType;
use crate::types::ResonanceEntry;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Structured outcome from the simworld after an action is applied.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WorldOutcome {
    pub resource_delta: f64,
    pub social_score: f64,
    pub harm_score: f64,
    pub truth_score: f64,
    pub kindness_score: f64,
    pub logic_score: f64,
    pub utility_score: f64,
    pub matches_expected: bool,
}

/// All events that can be appended to the event log.
/// Variants are tagged in JSONL as `{"type": "...", "payload": {...}}`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", content = "payload")]
pub enum RuntimeEvent {
    CycleStarted {
        cycle_id: u64,
        timestamp: DateTime<Utc>,
    },
    ObservationReceived {
        cycle_id: u64,
        observation_len: usize,
        world_resources: f64,
    },
    /// A memory query was issued.
    MemoryQueried {
        cycle_id: u64,
        query: String,
    },
    /// A memory retrieval returned hits.
    MemoryHitReturned {
        cycle_id: u64,
        hit_count: usize,
        top_key: Option<String>,
        top_value: Option<String>,
    },
    CandidateGenerated {
        cycle_id: u64,
        action_type: ActionType,
        score: f64,
        reasoning: Option<String>,
    },
    /// A candidate was rejected by the critic.
    CandidateRejected {
        cycle_id: u64,
        action_type: ActionType,
        reason: String,
    },
    CandidateSelected {
        cycle_id: u64,
        action_type: ActionType,
        score: f64,
        resonance: Vec<ResonanceEntry>,
        reasoning: Option<String>,
    },
    ActionApplied {
        cycle_id: u64,
        action_type: ActionType,
        conserve: bool,
    },
    WorldStateUpdated {
        cycle_id: u64,
        outcome: WorldOutcome,
    },
    RuntimeModeChanged {
        from: String,
        to: String,
    },
    MemoryWritten {
        cycle_id: u64,
        key: String,
    },
    ScratchpadUpdated {
        cycle_id: u64,
        entry_count: usize,
    },
    ErrorOccurred {
        cycle_id: u64,
        message: String,
    },
    /// An archive commit was performed.
    ArchiveCommitted {
        cycle_id: u64,
        frame_id: String,
        entry_count: usize,
    },
    /// A contradiction was detected between two claims.
    ContradictionDetected {
        cycle_id: u64,
        claim_a: String,
        claim_b: String,
        subject: String,
    },
    /// Evidence was stored in the evidence vault.
    EvidenceStored {
        cycle_id: u64,
        entry_id: String,
        source: String,
        confidence: f64,
        content_hash: String,
    },
    /// An evidence vault integrity check was performed.
    EvidenceIntegrityChecked {
        cycle_id: u64,
        total: usize,
        valid: usize,
        tampered: usize,
        all_valid: bool,
    },
    /// A contradiction was resolved (old claim superseded).
    ContradictionResolved {
        cycle_id: u64,
        superseded_claim: String,
        active_claim: String,
        resolution: String,
    },
    // ── Symbolic events ─────────────────────────────────────────────────
    /// A symbol was activated in the symbolic graph.
    SymbolActivated {
        cycle_id: u64,
        symbol_id: String,
        glyph: String,
        activation: f64,
    },
    /// Two symbols were linked in the symbolic graph.
    SymbolLinked {
        cycle_id: u64,
        source_id: String,
        target_id: String,
        edge_kind: String,
    },
    /// A symbolic trace was recorded (frame written).
    SymbolicTraceRecorded {
        cycle_id: u64,
        frame_id: String,
        symbol_count: usize,
        edge_count: usize,
    },
    /// A concept blend was generated by the creative stream.
    ConceptBlendGenerated {
        cycle_id: u64,
        blend_id: String,
        principle_key: String,
        action_type: ActionType,
    },
    /// A principle was extracted from memory.
    PrincipleExtracted {
        cycle_id: u64,
        principle_key: String,
        source_frame: Option<String>,
        confidence: f64,
    },
    /// Symbolic compression was applied (old frame reduced).
    SymbolicCompressionApplied {
        cycle_id: u64,
        source_frame_id: String,
        compressed_frame_id: String,
        compression_ratio: f64,
    },
    /// A resonance score was computed for a candidate.
    ResonanceScoreComputed {
        cycle_id: u64,
        action_type: ActionType,
        entries: Vec<ResonanceEntry>,
        total_score: f64,
    },
}

impl RuntimeEvent {
    /// The cycle ID carried by this event, if any.
    pub fn cycle_id(&self) -> Option<u64> {
        match self {
            Self::CycleStarted { cycle_id, .. }
            | Self::ObservationReceived { cycle_id, .. }
            | Self::MemoryQueried { cycle_id, .. }
            | Self::MemoryHitReturned { cycle_id, .. }
            | Self::CandidateGenerated { cycle_id, .. }
            | Self::CandidateRejected { cycle_id, .. }
            | Self::CandidateSelected { cycle_id, .. }
            | Self::ActionApplied { cycle_id, .. }
            | Self::WorldStateUpdated { cycle_id, .. }
            | Self::MemoryWritten { cycle_id, .. }
            | Self::ScratchpadUpdated { cycle_id, .. }
            | Self::ErrorOccurred { cycle_id, .. }
            | Self::ArchiveCommitted { cycle_id, .. }
            | Self::EvidenceStored { cycle_id, .. }
            | Self::EvidenceIntegrityChecked { cycle_id, .. }
            | Self::ContradictionDetected { cycle_id, .. }
            | Self::ContradictionResolved { cycle_id, .. }
            | Self::SymbolActivated { cycle_id, .. }
            | Self::SymbolLinked { cycle_id, .. }
            | Self::SymbolicTraceRecorded { cycle_id, .. }
            | Self::ConceptBlendGenerated { cycle_id, .. }
            | Self::PrincipleExtracted { cycle_id, .. }
            | Self::SymbolicCompressionApplied { cycle_id, .. }
            | Self::ResonanceScoreComputed { cycle_id, .. } => Some(*cycle_id),
            Self::RuntimeModeChanged { .. } => None,
        }
    }
}
